version: "3"

services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: marktia
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./marktia-db/data:/var/lib/mysql
    healthcheck:
      test: "exit 0"

  springboot-app:
    container_name: springboot-app
    image: springboot-app
    build:
      context: ./marktia-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_healthy